### ISSUE TITLE
Backporting commits.

### ISSUE THREAD

**Issue by Ferada** [Ferada/cl-cffi-gtk#29]
Should:
- [ ] 7d15f5afe98654ce601d75e77c858c22f3c8b86a (just the error handling bit)
- [ ] ed4dfe35c87100d36b03ac06d1d66a65d1fd44b5, a25c15b48aebfbbbf38c77bdac123df558733f8b (dialog handling, pr #23)
- [ ] 01c913c3998a9b3b2b182171b8a3e64b8c69340e (`g-file-new-for-uri`, pr #22)
- [ ] 93a9b08d609427f898cf3f8bb7db8291dc14692e, 08d23ff98c1deb2e37c1c0bd6bd46246f261053e (threading, pr #21)
- [ ] pr #18 would be good
- [ ] 2c3b210326a97e39431a0151d4981ac6e8e58867
- [ ] f91eeedc1ad15e8d4afa7289514105ac9f12a473
- [ ] 34c34820af9cf217499a3dd5c121ef5917207b03
- [ ] 16a71129efd85f7ca24055a32f17e6b06eac9cba (would be good, probably more complicated)
- [ ] 0709db654b6ed6da1be055e3acc31e0772aaa088 (CSS)
- [ ] pr #13

Non-exhaustive. It's actually quite a long list of small fixes over the time.

Actually might be easier to compare before after side by side and make new commits if things changed.

Probably not:
- GStreamer
- OpenGL things
